name: Super-Linter

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        env: 
          secret: ${{ secrets.test }}
        run: echo "$secret is invisible" "test dayo"
